In [1]:
import pandas as pd

# 一个最简单的Series
l = [1,2,3,4,5]
s1 = pd.Series(data=l)
s1

0    1
1    2
2    3
3    4
4    5
dtype: int64

In [2]:
# 指定以字符串ABCDE构成的字符串序列作为data的索引
s2 = pd.Series(data=l,index=list('ABCDE'),dtype='float32')
s2

A    1.0
B    2.0
C    3.0
D    4.0
E    5.0
dtype: float32

In [3]:
# 指定一个字典来创建一个Series
dicts = {'A': 1, 'B': 2, 'C': 3, 'D': 4, 'E': 5}
dicts
s3 = pd.Series(data=dicts,name='pandas_demo')
s3

A    1
B    2
C    3
D    4
E    5
Name: pandas_demo, dtype: int64

In [7]:
import pandas as pd
import numpy as np

# 特别的，对于numpy中的NaN以及Python中的None类型，在Series里直接显示缺省值NaN
l = [0,1,7,9,np.nan,None,1024,1024,512]
s4 = pd.Series(data=l)
s4

0       0.0
1       1.0
2       7.0
3       9.0
4       NaN
5       NaN
6    1024.0
7    1024.0
8     512.0
dtype: float64

In [13]:
# 1.使用list创建一个DataFrame
data = [
    ['laoan',30],
    ['laoli',29],
    ['lijianbing',39],
    ['hupeng',20],
    ['luotianyun',23]
]
df = pd.DataFrame(data,columns=['name','age'])
df

         name  age
0       laoan   30
1       laoli   29
2  lijianbing   39
3      hupeng   20
4  luotianyun   23

In [14]:
# 2.使用ndarray创建一个DataFrame
df = pd.DataFrame(data=np.random.randint(60,100,(6,4)),dtype='int32',columns=['Python','Java','C++','Ruby'],index=['laoan','laoli','lijianbing','luotiayun','hupeng','huxiaodong'])
df

            Python  Java  C++  Ruby
laoan           73    68   67    80
laoli           77    65   85    83
lijianbing      76    68   77    85
luotiayun       60    78   67    60
hupeng          95    83   91    81
huxiaodong      61    78   64    96

In [15]:
# 3.使用字典创建一个DataFrame;
# 方法1：字典按照如下格式构造：
'''
data = {
'列1名称':[该列所有值...],
'列2名称':[该列所有值...],
...
}
'''

df = pd.DataFrame(data={'Site':['Google', 'Runoob', 'Wiki'], 'Age':[10, 12, 13]})
df

     Site  Age
0  Google   10
1  Runoob   12
2    Wiki   13

In [16]:
# 方法2：字典按照如下格式构造：
'''
data = [
{'列1名称':值1,'列2名称':值2,...},
{'列1名称':值1,'列2名称':值2,...},
{'列1名称':值1,'列2名称':值2,...},
...
]

'''

df = pd.DataFrame([{'a': 1, 'b': 2},{'a': 5, 'b': 10, 'c': 20}])
df

   a   b     c
0  1   2   NaN
1  5  10  20.0

In [17]:
df = pd.DataFrame(data = np.random.randint(0,151,size = (150,3)),index = None,columns=['Python','Math','En'])
df.head(10) # 显示头部10⾏，默认5个
df.tail(10) # 显示末尾10⾏，默认5个
df.shape # 查看形状，⾏数和列数
df.dtypes # 查看数据类型
df.index # ⾏索引
df.columns # 列索引
df.values # 对象值，⼆维ndarray数组
df.describe() # 查看数值型列的汇总统计,计数、平均值、标准差、最⼩值、四分位数、最⼤值
df.info() # 查看列索引、数据类型、⾮空计数和内存信息

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 150 entries, 0 to 149
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   Python  150 non-null    int32
 1   Math    150 non-null    int32
 2   En      150 non-null    int32
dtypes: int32(3)
memory usage: 1.9 KB

In [18]:
# 准备数据
import pandas as pd
import numpy as np

df = pd.DataFrame(data=np.random.randint(60,100,(40,5)),columns=['Python','Java','C++','Ruby','数据结构'],index=['学生_000{}'.format(num) for num in range(1,41)])

# 在当前文件路径下保存数据为csv文件，文件名称为grade.csv，分隔符为","号
df.to_csv('./02th_grade.csv',sep=',',header=True, index=True)

In [19]:
# 使用Spider抓取懂车帝数值型数据后打包为对应格式数据并使用pandas将数据写入到csv文件；
# Packages and Modules import statements
# --------------------------------------
import requests
import pandas as pd
import numpy as np
from lxml import etree


# codings
# --------------------------------------

class DongchediSpider(object):
    '''
    采集懂车帝车辆评分的数值型数据
    '''

    def __init__(self):
        self.__headers = {
            'User-Agent':'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/106.0.0.0 Safari/537.36'
        }

    @property
    def headers(self):
        return self.__headers

    def __get_requests(self,url='',headers=None,method='GET',form_data=''):

        if method == 'GET':
            return requests.get(url=url,headers=headers)
        else:
            return requests.post(url=url,headers=headers,data=form_data)

    # 公共接口封装
    def get_requests(self,url='',headers=None,method='GET',form_data=''):

        return self.__get_requests(url=url,headers=headers,method=method,form_data=form_data)

    def __parse_data(self,data):
        '''
        解析一页数据
        :param data:str类型；
        :return: list类型
        '''

        dom = etree.HTML(data)
        comments = dom.xpath('//section[@class="tw-col-span-40 md:tw-col-span-29"]/article')
        page_data = []

        for comment in comments:
            # 字段数据依次解析

            # 作者id
            auther_id = comment.xpath(
                './aside[@class="tw-col-span-40 xl:tw-col-span-12 xl:tw-pr-12"]/header/div[@class="tw-ml-12 tw-flex tw-flex-col tw-justify-center"]/h2/a/text()')[
                0]

            # 总评分
            finall_score = comment.xpath(
                './section[@class="tw-col-span-40 tw-pt-16 xl:tw-col-span-28 tw-p-12 xl:tw-pt-0"]/header/a/span[1]/text()')[
                0]

            # 购车价格
            buy_car_price = '' if not comment.xpath('./aside/section/div[2]/div[1]/div[3]/p[1]/text()') else comment.xpath('./aside/section/div[2]/div[1]/div[3]/p[1]/text()')[0]

            # 续航公里数
            xuhang = '' if not comment.xpath('./aside/section/div[2]/div[1]/div[4]/p[1]/text()') else comment.xpath('./aside/section/div[2]/div[1]/div[4]/p[1]/text()')[0]

            # 一组核心的数值数据采集
            waiguan_score = '' if not comment.xpath('./aside/section/div[2]/div[2]/div[2]/p[1]/text()') else comment.xpath('./aside/section/div[2]/div[2]/div[2]/p[1]/text()')[0]

            neishi_score = '' if not comment.xpath('./aside/section/div[2]/div[2]/div[3]/p[1]/text()') else comment.xpath('./aside/section/div[2]/div[2]/div[3]/p[1]/text()')[0]

            peizhi_score = '' if not comment.xpath('./aside/section/div[2]/div[2]/div[4]/p[1]/text()') else comment.xpath('./aside/section/div[2]/div[2]/div[4]/p[1]/text()')[0]

            kongjian_score = '' if not comment.xpath('./aside/section/div[2]/div[2]/div[5]/p[1]/text()') else comment.xpath('./aside/section/div[2]/div[2]/div[5]/p[1]/text()')[0]

            shushixing_score = '' if not comment.xpath('./aside/section/div[2]/div[2]/div[6]/p[1]/text()') else comment.xpath('./aside/section/div[2]/div[2]/div[6]/p[1]/text()')[0]

            caokong_score = '' if not comment.xpath('./aside/section/div[2]/div[2]/div[7]/p[1]/text()') else comment.xpath('./aside/section/div[2]/div[2]/div[7]/p[1]/text()')[0]

            dongli_score = '' if not comment.xpath('./aside/section/div[2]/div[2]/div[8]/p[1]/text()') else comment.xpath('./aside/section/div[2]/div[2]/div[8]/p[1]/text()')[0]


            line = [auther_id,finall_score,waiguan_score,neishi_score,peizhi_score,kongjian_score,shushixing_score,caokong_score,dongli_score]
            page_data.append(line)

        return page_data

    def __cleaner_data(self,data):
        '''
        数据的简单清洗：将显示为'-'的数据置为0；将''的数据也置为0
        :param data:
        :return:
        '''

        for row in data:
            for col_index in range(len(row)):
                if row[col_index] == '-' or row[col_index] == '':
                    row[col_index] = 0

        return data

    def getDataFrame(self,data):
        '''
        将待写入数据构造为dataframe结构
        :return:
        '''

        data_frame = pd.DataFrame(data=data,columns=['作者id','总评分','外观评分','内饰评分','配置评分','空间评分','舒适性评分','操控评分','动力评分'])

        return data_frame

    def write_to_csv(self,dataframes):
        '''

        :param dataframes:
        :return:
        '''

        dataframes.to_csv('./02th_dongchediData.csv',sep=';')
        
    def display(self):

        url = 'https://www.dongchedi.com/auto/series/score/4363-x-S0-x-x-x-{}'

        pages = int(input('请输入采集数据的页数>>>：'))

        final_result = []
        print('开始采集数据...')
        for i in range(1,pages + 1):

            url = url.format(i)

            # 请求一页数据
            html = self.__get_requests(url=url,headers=self.__headers).text

            # 解析一页数据
            page_data = self.__parse_data(html)

            # 清洗数据
            final_page_data = self.__cleaner_data(page_data)
            for row in final_page_data:
                final_result.append(row)
            # print(page_data)

        print('开始数据写入...')
        # 最后的数据写入
        self.write_to_csv(self.getDataFrame(final_result))

def test():
    DongchediSpider().display()



# run test UseCase if current modules is main
if __name__ == '__main__':
    test()

开始采集数据...
开始数据写入...

In [20]:
df1 = pd.read_csv('./02th_dongchediData.csv',sep=',')
df1.head(10)

  ;作者id;总评分;外观评分;内饰评分;配置评分;空间评分;舒适性评分;操控评分;动力评分
0                0;安迪想开我的车;4.56;5;4.5;5;5;5;5;0
1                1;梦幻宇宙72;4.5;3;4;4.5;5;5;4.5;0
2                     2;艳子琐事;4.07;4;4;4;4;4;4;0
3         3;WayneTheLion;4.57;4.5;4;4.5;5;4;5;0
4             4;Terry8620;4;4.5;3;4;4;3.5;4.5;0
5                   5;亨利Sun;4.5;5;4;5;4.5;3;5;0
6          6;vincann;4.36;5;4;4.5;4.5;3.5;4.5;0
7               7;酱油卡俄斯;4.5;5;3.5;4.5;5;3.5;5;0
8                      8;成熟咖啡Qu;4;4;4;4;4;4;4;0
9          9;高不浅;4.39;4.5;4.5;4.5;4.5;3.5;4.5;0

In [22]:
# 数据准备
df1 = pd.DataFrame(data = np.random.randint(0,50,size = [50,5]), columns=['IT','化⼯','⽣物','教师','⼠兵'])
df2 = pd.DataFrame(data = np.random.randint(0,50,size = [150,3]),columns=['Python','Tensorflow','Keras'])

# 写入数据至表格
df1.to_excel(excel_writer='./02th_salary.xlsx',sheet_name='salary',na_rep='',header=True,index=True)

In [23]:
df = pd.read_excel('./02th_salary.xlsx',sheet_name=0,header=0)
df.head(10)

   Unnamed: 0  IT  化⼯  ⽣物  教师  ⼠兵
0           0  42  43  14   9   7
1           1  46   1  20  36  48
2           2  18  48   9  32  13
3           3  43  42  22  26  29
4           4  48  20  25  48  23
5           5  39  21  17   2  17
6           6  36  28  34   1  20
7           7   5   6   9   5   0
8           8  48  16   4  15  21
9           9  16  19  38  15  18

In [24]:
with pd.ExcelWriter('./02th_data.xlsx') as writer:
    df1.to_excel(writer,sheet_name='salary',index = False)
    df2.to_excel(writer,sheet_name='score',index = False)

In [28]:
pd.read_excel('./02th_data.xlsx',sheet_name='score')
df.head(10)

   Unnamed: 0  IT  化⼯  ⽣物  教师  ⼠兵
0           0  42  43  14   9   7
1           1  46   1  20  36  48
2           2  18  48   9  32  13
3           3  43  42  22  26  29
4           4  48  20  25  48  23
5           5  39  21  17   2  17
6           6  36  28  34   1  20
7           7   5   6   9   5   0
8           8  48  16   4  15  21
9           9  16  19  38  15  18

In [29]:
# 数据准备
df2 = pd.DataFrame(data = np.random.randint(0,50,size = [150,3]),columns=['Python','Tensorflow','Keras'])
df2

     Python  Tensorflow  Keras
0        19          27     24
1        11           3     40
2        12          47     18
3        26          38     24
4        30           7     28
..      ...         ...    ...
145      44          25     44
146      16          31     36
147      27          37     29
148      45           9     19
149      27          47     18

[150 rows x 3 columns]

In [30]:
# 按给定列名称获取整列的数据；
df2['Python'].head(10)

0    19
1    11
2    12
3    26
4    30
5    37
6     9
7    44
8    42
9     3
Name: Python, dtype: int32

In [31]:
# 按列名属性获取整列数据；
df2.Python.head(10)

0    19
1    11
2    12
3    26
4    30
5    37
6     9
7    44
8    42
9     3
Name: Python, dtype: int32

In [32]:
# 同时获取多行
df2[['Python','Keras']].head(10)

   Python  Keras
0      19     24
1      11     40
2      12     18
3      26     24
4      30     28
5      37     15
6       9     26
7      44     13
8      42     15
9       3     46

In [35]:
# 数据准备
df = pd.DataFrame(data = np.random.randint(0,150,size = [10,3]),index = list('ABCDEFGHIJ'),columns=['Python','Tensorflow','Keras'])
df

   Python  Tensorflow  Keras
A     125          38     33
B      50          33    120
C      77         115     97
D     101          68     98
E      80         137     17
F     107          28     61
G     125          96     49
H     126          90      6
I     122           5     43
J      63         123    114

In [36]:
# 依据指定行索引进行依次取值；
df.loc[['A','C','D','F']]

   Python  Tensorflow  Keras
A     125          38     33
C      77         115     97
D     101          68     98
F     107          28     61

In [37]:
# 行索引切片，再按指定列索引取值；
df.loc['A':'E',['Python','Keras']]

   Python  Keras
A     125     33
B      50    120
C      77     97
D     101     98
E      80     17

In [38]:
# 行索引切片（效果为选取所有行），按指定列索引取值；
df.loc[:,['Keras','Tensorflow']]

   Keras  Tensorflow
A     33          38
B    120          33
C     97         115
D     98          68
E     17         137
F     61          28
G     49          96
H      6          90
I     43           5
J    114         123

In [39]:
# 行索引切片（效果为从E行开始，步长为2进行取值），列索引切片’
df.loc['E'::2,'Python':'Tensorflow']

   Python  Tensorflow
E      80         137
G     125          96
I     122           5

In [40]:
# 取第一行第一列的元素，常作为选取标量值
df.loc['A','Python']

np.int32(125)

In [41]:
# 数据准备
df = pd.DataFrame(data = np.random.randint(0,150,size = [10,3]),index = list('ABCDEFGHIJ'),columns=['Python','Tensorflow','Keras'])
df

   Python  Tensorflow  Keras
A      76          30     88
B      59          19     79
C     137          40     55
D      85         149     92
E      34          19     57
F      85         149    133
G     104         118     21
H      16          56     26
I      32          80    129
J      23          19     96

In [42]:
# 指定取第n行位置的元素
df.iloc[4]

Python        34
Tensorflow    19
Keras         57
Name: E, dtype: int32

In [43]:
# 行位置数值切片，列位置数值切片
df.iloc[2:8,0:2]

   Python  Tensorflow
C     137          40
D      85         149
E      34          19
F      85         149
G     104         118
H      16          56

In [44]:
# 指定行列位置数值取值
df.iloc[[1,3,5],[0,2,1]]

   Python  Keras  Tensorflow
B      59     79          19
D      85     92         149
F      85    133         149

In [45]:
# 行切片，保留所有列
df.iloc[1:3,:]

   Python  Tensorflow  Keras
B      59          19     79
C     137          40     55

In [46]:
# 列切片，保留所有行
df.iloc[:,:2]

   Python  Tensorflow
A      76          30
B      59          19
C     137          40
D      85         149
E      34          19
F      85         149
G     104         118
H      16          56
I      32          80
J      23          19

In [47]:
# 选取标量值
df.iloc[0,2]

np.int32(88)

In [48]:
# 数据准备
df = pd.DataFrame(data = np.random.randint(0,150,size = [10,3]),index = list('ABCDEFGHIJ'),columns=['Python','Tensorflow','Keras'])
df

   Python  Tensorflow  Keras
A     146          29     97
B       6          97     98
C     102          69     66
D      68          61     11
E      48          46      0
F     136          40     93
G       5         129    105
H      62         115     35
I     134          88     55
J      56         109     94

In [49]:
# Python课程成绩大于100分的
cond1 = df.Python > 100
df[cond1]

   Python  Tensorflow  Keras
A     146          29     97
C     102          69     66
F     136          40     93
I     134          88     55

In [50]:
# Python课程成绩大于50分且Keras成绩大于50分的
cond2 = (df.Python > 50) & (df['Keras'] > 50)
df[cond2]

   Python  Tensorflow  Keras
A     146          29     97
C     102          69     66
F     136          40     93
I     134          88     55
J      56         109     94

In [51]:
# 指定行标签的A、C、F行是否存在于dataframe，存在则返回
df[df.index.isin(['A','C','F'])]

   Python  Tensorflow  Keras
A     146          29     97
C     102          69     66
F     136          40     93

In [52]:
# 数据准备
df = pd.DataFrame(data = np.random.randint(0,150,size = [10,3]),index = list('ABCDEFGHIJ'),columns=['Python','Tensorflow','Keras'])
df

   Python  Tensorflow  Keras
A      60         141     60
B      13          75     74
C     131          36      1
D     109           1     57
E      57          99     90
F      41          56     51
G      89          88    113
H     126         121     23
I      75          96     40
J      15          96    127

In [53]:
# 准备一个Series
s=pd.Series(data=np.random.randint(0,150,size=9),index=list('BCDEFGHIJ'),name = 'PyTorch')
s

B     84
C     56
D      9
E     24
F     74
G     19
H      6
I     49
J    130
Name: PyTorch, dtype: int32

In [54]:
# 增加一列数据
df['PyTorch'] = s
df

   Python  Tensorflow  Keras  PyTorch
A      60         141     60      NaN
B      13          75     74     84.0
C     131          36      1     56.0
D     109           1     57      9.0
E      57          99     90     24.0
F      41          56     51     74.0
G      89          88    113     19.0
H     126         121     23      6.0
I      75          96     40     49.0
J      15          96    127    130.0

In [55]:
# 按行列索引名直接赋值
df.loc['A','Python'] = 256
df

   Python  Tensorflow  Keras  PyTorch
A     256         141     60      NaN
B      13          75     74     84.0
C     131          36      1     56.0
D     109           1     57      9.0
E      57          99     90     24.0
F      41          56     51     74.0
G      89          88    113     19.0
H     126         121     23      6.0
I      75          96     40     49.0
J      15          96    127    130.0

In [56]:
# 按行列位置数值直接赋值
df.iloc[3,2] = 512
df

   Python  Tensorflow  Keras  PyTorch
A     256         141     60      NaN
B      13          75     74     84.0
C     131          36      1     56.0
D     109           1    512      9.0
E      57          99     90     24.0
F      41          56     51     74.0
G      89          88    113     19.0
H     126         121     23      6.0
I      75          96     40     49.0
J      15          96    127    130.0

In [57]:
# 保留行，切片列后整列重新赋值
df.loc[:,'Python'] = np.array([128]*10)
df

C:\Users\10433\AppData\Local\Temp\ipykernel_23136\3399097105.py:2: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[128 128 128 128 128 128 128 128 128 128]' has dtype incompatible with int32, please explicitly cast to a compatible dtype first.
  df.loc[:,'Python'] = np.array([128]*10)

   Python  Tensorflow  Keras  PyTorch
A     128         141     60      NaN
B     128          75     74     84.0
C     128          36      1     56.0
D     128           1    512      9.0
E     128          99     90     24.0
F     128          56     51     74.0
G     128          88    113     19.0
H     128         121     23      6.0
I     128          96     40     49.0
J     128          96    127    130.0

In [58]:
# 依据boolean索引赋值；⼤于等于128变成原来的负数，否则不变
df[df >= 128] = -df
df

   Python  Tensorflow  Keras  PyTorch
A    -128        -141     60      NaN
B    -128          75     74     84.0
C    -128          36      1     56.0
D    -128           1   -512      9.0
E    -128          99     90     24.0
F    -128          56     51     74.0
G    -128          88    113     19.0
H    -128         121     23      6.0
I    -128          96     40     49.0
J    -128          96    127   -130.0

In [59]:
# 数据准备
df1 = pd.DataFrame(data = np.random.randint(0,150,size = [10,3]),index = list('ABCDEFGHIJ'),columns=['Python','Tensorflow','Keras'])

df2 = pd.DataFrame(data = np.random.randint(0,150,size = [10,3]),index = list('KLMNOPQRST'),columns=['Python','Tensorflow','Keras'])

df3 = pd.DataFrame(data = np.random.randint(0,150,size = (10,2)),index = list('ABCDEFGHIJ'),columns=['PyTorch','Paddle'])
df1, df2, df3

(   Python  Tensorflow  Keras
 A       8          20     76
 B     102          46    101
 C     100         109     61
 D     124          59    123
 E     119         123     65
 F      21          53     12
 G       6          12    125
 H      54          20      2
 I      58          80     16
 J     131          21     49,
    Python  Tensorflow  Keras
 K      29           9     33
 L     129          18     57
 M      57          20     20
 N      41         118    116
 O      60         130    123
 P     142          62     83
 Q      63          90     29
 R      43          19    100
 S      31         134    135
 T     126          30    103,
    PyTorch  Paddle
 A       39      99
 B      109     132
 C       42       3
 D      116      18
 E       35      72
 F       62     109
 G       96     136
 H      147      37
 I        7      62
 J       44      16)

In [61]:
# df1和df2行串联，df2的行追加在df1的行后面
df_out = pd.concat([df1,df2],axis = 0) 
df_out

   Python  Tensorflow  Keras
A       8          20     76
B     102          46    101
C     100         109     61
D     124          59    123
E     119         123     65
F      21          53     12
G       6          12    125
H      54          20      2
I      58          80     16
J     131          21     49
K      29           9     33
L     129          18     57
M      57          20     20
N      41         118    116
O      60         130    123
P     142          62     83
Q      63          90     29
R      43          19    100
S      31         134    135
T     126          30    103

In [63]:
# df1和df3列串联，df3的列追加在df1的列后面
df_out = pd.concat([df1,df3],axis = 1) 
df_out

   Python  Tensorflow  Keras  PyTorch  Paddle
A       8          20     76       39      99
B     102          46    101      109     132
C     100         109     61       42       3
D     124          59    123      116      18
E     119         123     65       35      72
F      21          53     12       62     109
G       6          12    125       96     136
H      54          20      2      147      37
I      58          80     16        7      62
J     131          21     49       44      16

In [64]:
# 数据准备
df = pd.DataFrame(data = np.random.randint(0,151,size = (10,3)),index = list('ABCDEFGHIJ'),columns = ['Python','Keras','Tensorflow'])
df

   Python  Keras  Tensorflow
A      22     44          95
B      88     70         141
C      57     41          87
D     132     73         131
E     140    113          29
F      17     14          72
G     145     46           8
H      22     44         129
I     112    108          51
J      21    149           6

In [67]:
# 表中新增一行数据
df = pd.concat([df,pd.DataFrame(data = np.random.randint(0,150,size = [1,3]),index=list('K'),columns = ['Python','Keras','Tensorflow'])],axis = 0)
df

   Python  Keras  Tensorflow
A      22     44          95
B      88     70         141
C      57     41          87
D     132     73         131
E     140    113          29
F      17     14          72
G     145     46           8
H      22     44         129
I     112    108          51
J      21    149           6
K      56     36          88

In [68]:
# 数据准备
df1 = pd.DataFrame(data = {'name':['softpo','Daniel','Brandon','Ella'],'weight':[70,55,75,65]})
df2 = pd.DataFrame(data = {'name':['softpo','Daniel','Brandon','Cindy'],'height':[172,170,170,166]})
df3 = pd.DataFrame(data = {'名字':['softpo','Daniel','Brandon','Cindy'],'height':[172,170,170,166]})
df1, df2, df3

(      name  weight
 0   softpo      70
 1   Daniel      55
 2  Brandon      75
 3     Ella      65,
       name  height
 0   softpo     172
 1   Daniel     170
 2  Brandon     170
 3    Cindy     166,
         名字  height
 0   softpo     172
 1   Daniel     170
 2  Brandon     170
 3    Cindy     166)

In [69]:
# 内连接
df_out = pd.merge(df1,df2,how='inner',on='name')
df_out

      name  weight  height
0   softpo      70     172
1   Daniel      55     170
2  Brandon      75     170

In [70]:
# 全外连接
df_out = pd.merge(df1,df3,how='outer',left_on='name',right_on='名字')
df_out

      name  weight       名字  height
0  Brandon    75.0  Brandon   170.0
1      NaN     NaN    Cindy   166.0
2   Daniel    55.0   Daniel   170.0
3     Ella    65.0      NaN     NaN
4   softpo    70.0   softpo   172.0

In [71]:
# 左外连接
df_out = pd.merge(df1,df2,how='left',left_on='name',right_on='name')
df_out

      name  weight  height
0   softpo      70   172.0
1   Daniel      55   170.0
2  Brandon      75   170.0
3     Ella      65     NaN

In [72]:
# 右外连接
df_out = pd.merge(df1,df2,how='right',left_on='name',right_on='name')
df_out

      name  weight  height
0   softpo    70.0     172
1   Daniel    55.0     170
2  Brandon    75.0     170
3    Cindy     NaN     166

In [74]:
# 数据准备
df = pd.DataFrame(data = {
    'color':['red','blue','red','green','blue',None,'red'],
    'price':[10,20,10,15,20,0,np.nan]
})
df

   color  price
0    red   10.0
1   blue   20.0
2    red   10.0
3  green   15.0
4   blue   20.0
5   None    0.0
6    red    NaN

In [75]:
# 检查是否有重复数据；置为True的元素代表重复
df.duplicated()

0    False
1    False
2     True
3    False
4     True
5    False
6    False
dtype: bool

In [76]:
# 删除重复的元素
df.drop_duplicates()

   color  price
0    red   10.0
1   blue   20.0
3  green   15.0
5   None    0.0
6    red    NaN

In [77]:
# 判断是否存在空值
df.isnull()

   color  price
0  False  False
1  False  False
2  False  False
3  False  False
4  False  False
5   True  False
6  False   True

In [78]:
# 只要有空值的行全部删除
df.dropna(how = 'any')

   color  price
0    red   10.0
1   blue   20.0
2    red   10.0
3  green   15.0
4   blue   20.0

In [79]:
# 为空的值进行填充
df.fillna(value=123)

   color  price
0    red   10.0
1   blue   20.0
2    red   10.0
3  green   15.0
4   blue   20.0
5    123    0.0
6    red  123.0

In [80]:
# 数据准备
df = pd.DataFrame(np.array(([3,7,1], [2, 8, 256])),index=['dog', 'cat'],columns=['China', 'America', 'France'])
df

     China  America  France
dog      3        7       1
cat      2        8     256

In [81]:
# 过滤查看如下字段的值
df.filter(items=['China', 'France'])

     China  France
dog      3       1
cat      2     256

In [82]:
# 依据正则表达式过滤：查看以字母a结尾的列索引
df.filter(regex='a$', axis=1)

     China  America
dog      3        7
cat      2        8

In [83]:
# 依据正则表达式过滤查看以字母d开头的行索引
df.filter(regex='^d', axis=0)

     China  America  France
dog      3        7       1

In [84]:
# 使用模糊匹配：索引名包含ca的行索引
df.filter(like='ca', axis=0)

     China  America  France
cat      2        8     256

In [85]:
# 数据准备
df2 = pd.DataFrame(data = np.random.randn(10000,3)) # 正态分布数据
df2

             0         1         2
0     0.768802  0.267979 -1.124040
1    -0.930826  0.263063  0.401559
2     0.699855  0.822491  1.928767
3    -1.132741 -0.396887 -0.003282
4    -0.086634  0.061756  0.224634
...        ...       ...       ...
9995 -0.443224 -1.091584 -0.759261
9996  0.075462 -1.648475 -0.185007
9997  1.289411  0.283192  0.972076
9998  0.637182 -0.468186  2.143523
9999  0.769699  0.847469 -0.825356

[10000 rows x 3 columns]

In [86]:
# 创建boolean索引
cond = (df2 > 3*df2.std()).any(axis = 1)
cond

0       False
1       False
2       False
3       False
4       False
        ...
9995    False
9996    False
9997    False
9998    False
9999    False
Length: 10000, dtype: bool

In [87]:
# 找出不满足条件的索引
index = df2[cond].index
index

Index([  39,  560, 1406, 1557, 1610, 1918, 1950, 2467, 2578, 2607, 2617, 2819,
       2972, 3311, 3466, 3544, 3615, 3624, 3637, 4048, 5127, 5143, 5144, 5608,
       5789, 6061, 6138, 6204, 6603, 6941, 6987, 7096, 7143, 7392, 7766, 7837,
       8155, 8228, 8442, 8633, 8640, 8936, 9583],
      dtype='int64')

In [88]:
# 依据匹配索引进行删除
df2.drop(labels=index,axis = 0)

             0         1         2
0     0.768802  0.267979 -1.124040
1    -0.930826  0.263063  0.401559
2     0.699855  0.822491  1.928767
3    -1.132741 -0.396887 -0.003282
4    -0.086634  0.061756  0.224634
...        ...       ...       ...
9995 -0.443224 -1.091584 -0.759261
9996  0.075462 -1.648475 -0.185007
9997  1.289411  0.283192  0.972076
9998  0.637182 -0.468186  2.143523
9999  0.769699  0.847469 -0.825356

[9957 rows x 3 columns]

In [89]:
# 数据准备
df = pd.DataFrame(data = np.random.randint(0,10,size = (10,3)),index = list('ABCDEFHIJK'),columns=['Python','Tensorflow','Keras'])
df

   Python  Tensorflow  Keras
A       6           3      6
B       8           4      6
C       7           1      7
D       3           2      1
E       4           4      7
F       4           3      3
H       9           8      0
I       9           3      3
J       3           7      2
K       9           8      2

In [90]:
# 第5行第3列的值置为空
df.iloc[4,2] = None # 空数据
df

   Python  Tensorflow  Keras
A       6           3    6.0
B       8           4    6.0
C       7           1    7.0
D       3           2    1.0
E       4           4    NaN
F       4           3    3.0
H       9           8    0.0
I       9           3    3.0
J       3           7    2.0
K       9           8    2.0

In [91]:
# 重命名轴索引：将行索引和列索引中指定的索引值重置
df.rename(index = {'A':'AA','B':'BB'},columns = {'Python':'⼈⼯智能'})

    ⼈⼯智能  Tensorflow  Keras
AA     6           3    6.0
BB     8           4    6.0
C      7           1    7.0
D      3           2    1.0
E      4           4    NaN
F      4           3    3.0
H      9           8    0.0
I      9           3    3.0
J      3           7    2.0
K      9           8    2.0

In [93]:
# 替换值
df = df.replace(3,1024) #将3替换为1024
df = df.replace([0,7],2048) # 将0和7替换为2048
df = df.replace({0:512,np.nan:998}) # 根据字典键值对进⾏替换
df = df.replace({'Python':2},-1024) # 将Python这⼀列中等于2的，替换为-1024
df

   Python  Tensorflow   Keras
A       6        1024     6.0
B       8           4     6.0
C    2048           1  2048.0
D    1024           2     1.0
E       4           4   998.0
F       4        1024  1024.0
H       9           8  2048.0
I       9        1024  1024.0
J    1024        2048     2.0
K       9           8     2.0

In [97]:
# 数据准备
df = pd.DataFrame(data = np.random.randint(0,10,size = (10,3)),index = list('ABCDEFHIJK'),columns=['Python','Tensorflow','Keras'])
df

   Python  Tensorflow  Keras
A       0           9      1
B       8           7      8
C       2           4      4
D       2           8      5
E       7           1      9
F       1           0      3
H       1           2      3
I       4           5      1
J       8           4      1
K       0           0      9

In [98]:
# 1、map批量元素改变
df['Keras'].map({1:'Hello',5:'World',7:'AI'}) # 字典映射

A    Hello
B      NaN
C      NaN
D    World
E      NaN
F      NaN
H      NaN
I    Hello
J    Hello
K      NaN
Name: Keras, dtype: object

In [99]:
# 普通函数映射：值与3做取余，余数为0的映射为True，否则映射为False
def convert(x):
    if x%3 == 0:
        return True
    else:
        return False

# 函数作为参数传递给map
df['Tensorflow'].map(convert)

A     True
B    False
C    False
D    False
E    False
F     True
H    False
I    False
J    False
K     True
Name: Tensorflow, dtype: bool

In [100]:
# 匿名函数映射：值大于5的映射为True，否则映射为False
df['Python'].map(lambda x:True if x >=5 else False)

A    False
B     True
C    False
D    False
E     True
F    False
H    False
I    False
J     True
K    False
Name: Python, dtype: bool

In [101]:
# 数据准备
df = pd.DataFrame(data = np.random.randint(0,10,size = (10,3)),index = list('ABCDEFHIJK'),columns=['Python','Tensorflow','Keras'])
df

   Python  Tensorflow  Keras
A       3           2      1
B       8           7      8
C       2           5      4
D       2           8      3
E       6           7      6
F       5           0      7
H       7           0      4
I       5           2      6
J       9           8      1
K       6           8      7

In [102]:
# 匿名函数映射：值大于5的映射为True，否则映射为False
df['Keras'].apply(lambda x:True if x >5 else False)

A    False
B     True
C    False
D    False
E     True
F     True
H    False
I     True
J    False
K     True
Name: Keras, dtype: bool

In [103]:
# 此时就是DataFrame调用apply方法，其中的x是DataFrame中列或者⾏，是一个Series
# 匿名函数映射：将指定的列或行的值映射为该列或行所有值的中位数
df.apply(lambda x : x.median(),axis = 0)

Python        5.5
Tensorflow    6.0
Keras         5.0
dtype: float64

In [104]:
# 普通函数映射：行索引求均值和计数
def convert(x):
    return (round(x.mean(),1),x.count())

df.apply(convert,axis = 1)

A    (2.0, 3)
B    (7.7, 3)
C    (3.7, 3)
D    (4.3, 3)
E    (6.3, 3)
F    (4.0, 3)
H    (3.7, 3)
I    (4.3, 3)
J    (6.0, 3)
K    (7.0, 3)
dtype: object

In [105]:
# 另外，还有个applymap方法，将dataframe中的每一个值做映射，如下例子：
# 计算DataFrame中每个元素都加100的值
df.applymap(lambda x : x + 100)

C:\Users\10433\AppData\Local\Temp\ipykernel_23136\999424730.py:3: FutureWarning: DataFrame.applymap has been deprecated. Use DataFrame.map instead.
  df.applymap(lambda x : x + 100)

   Python  Tensorflow  Keras
A     103         102    101
B     108         107    108
C     102         105    104
D     102         108    103
E     106         107    106
F     105         100    107
H     107         100    104
I     105         102    106
J     109         108    101
K     106         108    107

In [106]:
# 数据准备
df = pd.DataFrame(data = np.random.randint(0,10,size = (10,3)),index = list('ABCDEFHIJK'),columns=['Python','Tensorflow','Keras'])
df

   Python  Tensorflow  Keras
A       5           4      4
B       3           0      7
C       4           5      7
D       8           2      7
E       0           7      8
F       4           0      1
H       4           5      6
I       3           8      1
J       5           9      3
K       6           4      6

In [108]:
# 选取一个列，同时执行两个计算任务，返回同行索引数的两列结果值，以dataframe返回
df['Python'].transform([np.sqrt,np.exp, np.sin])

       sqrt          exp       sin
A  2.236068   148.413159 -0.958924
B  1.732051    20.085537  0.141120
C  2.000000    54.598150 -0.756802
D  2.828427  2980.957987  0.989358
E  0.000000     1.000000  0.000000
F  2.000000    54.598150 -0.756802
H  2.000000    54.598150 -0.756802
I  1.732051    20.085537  0.141120
J  2.236068   148.413159 -0.958924
K  2.449490   403.428793 -0.279415

In [110]:
# 数据准备
df = pd.DataFrame(data = np.random.randint(0,100,size = (20,3)),index = list('ABCDEFHIJKLMNOPQRSTU'),columns=['Python','Tensorflow','Keras'])
df

   Python  Tensorflow  Keras
A      25          95     23
B      41          81     69
C       2          72      8
D      15          97     81
E      14          85     50
F      61           3     63
H      64          16     31
I      87          66     23
J      65           9     87
K      42          58     34
L      21          81     20
M      32          78     59
N      38          71     52
O      13          63     22
P      81          15     68
Q      20          91     13
R      12          10     69
S      70          96     42
T       7          24     47
U      69          11     63

In [111]:
# 简单统计指标
df.count() # ⾮NA值的数量

Python        20
Tensorflow    20
Keras         20
dtype: int64

In [112]:
df.max(axis = 0) #轴0最⼤值，即每⼀列最⼤值

Python        87
Tensorflow    97
Keras         87
dtype: int32

In [113]:
df.min() #默认计算轴0最⼩值

Python        2
Tensorflow    3
Keras         8
dtype: int32

In [114]:
df.median() # 中位数

Python        35.0
Tensorflow    68.5
Keras         48.5
dtype: float64

In [115]:
df.sum() # 求和

Python         779
Tensorflow    1122
Keras          924
dtype: int64

In [116]:
df.mean(axis = 1) #轴1平均值，即每⼀⾏的平均值

A    47.666667
B    63.666667
C    27.333333
D    64.333333
E    49.666667
F    42.333333
H    37.000000
I    58.666667
J    53.666667
K    44.666667
L    40.666667
M    56.333333
N    53.666667
O    32.666667
P    54.666667
Q    41.333333
R    30.333333
S    69.333333
T    26.000000
U    47.666667
dtype: float64

In [117]:
df.quantile(q = [0.2,0.4,0.8]) # 分位数

     Python  Tensorflow  Keras
0.2    13.8        14.2   22.8
0.4    23.4        61.0   38.8
0.8    65.8        86.2   68.2

In [118]:
df.describe() # 查看数值型列的汇总统计,计数、平均值、标准差、最⼩值、四分位数、最⼤值

        Python  Tensorflow      Keras
count  20.0000   20.000000  20.000000
mean   38.9500   56.100000  46.200000
std    26.8102   34.564813  23.480339
min     2.0000    3.000000   8.000000
25%    14.7500   15.750000  23.000000
50%    35.0000   68.500000  48.500000
75%    64.2500   82.000000  64.250000
max    87.0000   97.000000  87.000000

In [119]:
# 计算某一列下最小值元素所处第几行
df['Python'].argmin()

np.int64(2)

In [120]:
# 计算某一列下最大值元素所处第几行
df['Tensorflow'].argmax()

np.int64(3)

In [121]:
# 获得最大值、最小值的元素的索引是多少
df.idxmax(), df.idxmin()

(Python        I
 Tensorflow    D
 Keras         J
 dtype: object,
 Python        C
 Tensorflow    F
 Keras         C
 dtype: object)

In [122]:
df['Python'].value_counts() # 统计元素出现次数

Python
25    1
41    1
2     1
15    1
14    1
61    1
64    1
87    1
65    1
42    1
21    1
32    1
38    1
13    1
81    1
20    1
12    1
70    1
7     1
69    1
Name: count, dtype: int64

In [123]:
df['Keras'].unique() # 去重

array([23, 69,  8, 81, 50, 63, 31, 87, 34, 20, 59, 52, 22, 68, 13, 42, 47],
      dtype=int32)

In [124]:
df.cumsum() # 累加

   Python  Tensorflow  Keras
A      25          95     23
B      66         176     92
C      68         248    100
D      83         345    181
E      97         430    231
F     158         433    294
H     222         449    325
I     309         515    348
J     374         524    435
K     416         582    469
L     437         663    489
M     469         741    548
N     507         812    600
O     520         875    622
P     601         890    690
Q     621         981    703
R     633         991    772
S     703        1087    814
T     710        1111    861
U     779        1122    924

In [125]:
df.cumprod() # 累乘

                Python           Tensorflow                Keras
A                   25                   95                   23
B                 1025                 7695                 1587
C                 2050               554040                12696
D                30750             53741880              1028376
E               430500           4568059800             51418800
F             26260500          13704179400           3239384400
H           1680672000         219266870400         100420916400
I         146218464000       14471613446400        2309681077200
J        9504200160000      130244521017600      200942253716400
K      399176406720000     7554182219020800     6832036626357600
L     8382704541120000   611888759740684800   136640732527152000
M   268246545315840000 -7612908961355240448  8061803219101968000
N -8253375351707631616 -5560958118645074944 -5061346302017351168
O  3386584870058098688   147775925841759232  -669154202124416000
P -2387786630937280512  2216638887626388480 -8608997597041184768
Q  7584499602383044608 -1200046036803716096 -1236504319278092288
R -1219725139951222784  6446283705672390656  6914922338359390208
S  6852960571962163200 -8346062761575251968 -4721166968258437120
T -7369508217393512448  2608678532999020544  -533918623631925248
U  8012767063715086336 -8198024284429877248  3256614858607812608

In [126]:
df.std() # 标准差

Python        26.810200
Tensorflow    34.564813
Keras         23.480339
dtype: float64

In [127]:
df.var() # ⽅差

Python         718.786842
Tensorflow    1194.726316
Keras          551.326316
dtype: float64

In [128]:
df.cummin() # 累计最⼩值

   Python  Tensorflow  Keras
A      25          95     23
B      25          81     23
C       2          72      8
D       2          72      8
E       2          72      8
F       2           3      8
H       2           3      8
I       2           3      8
J       2           3      8
K       2           3      8
L       2           3      8
M       2           3      8
N       2           3      8
O       2           3      8
P       2           3      8
Q       2           3      8
R       2           3      8
S       2           3      8
T       2           3      8
U       2           3      8

In [129]:
df.cummax() # 累计最⼤值

   Python  Tensorflow  Keras
A      25          95     23
B      41          95     69
C      41          95     69
D      41          97     81
E      41          97     81
F      61          97     81
H      64          97     81
I      87          97     81
J      87          97     87
K      87          97     87
L      87          97     87
M      87          97     87
N      87          97     87
O      87          97     87
P      87          97     87
Q      87          97     87
R      87          97     87
S      87          97     87
T      87          97     87
U      87          97     87

In [130]:
df.diff() # 计算差分

   Python  Tensorflow  Keras
A     NaN         NaN    NaN
B    16.0       -14.0   46.0
C   -39.0        -9.0  -61.0
D    13.0        25.0   73.0
E    -1.0       -12.0  -31.0
F    47.0       -82.0   13.0
H     3.0        13.0  -32.0
I    23.0        50.0   -8.0
J   -22.0       -57.0   64.0
K   -23.0        49.0  -53.0
L   -21.0        23.0  -14.0
M    11.0        -3.0   39.0
N     6.0        -7.0   -7.0
O   -25.0        -8.0  -30.0
P    68.0       -48.0   46.0
Q   -61.0        76.0  -55.0
R    -8.0       -81.0   56.0
S    58.0        86.0  -27.0
T   -63.0       -72.0    5.0
U    62.0       -13.0   16.0

In [131]:
df.pct_change() # 计算百分⽐变化

     Python  Tensorflow     Keras
A       NaN         NaN       NaN
B  0.640000   -0.147368  2.000000
C -0.951220   -0.111111 -0.884058
D  6.500000    0.347222  9.125000
E -0.066667   -0.123711 -0.382716
F  3.357143   -0.964706  0.260000
H  0.049180    4.333333 -0.507937
I  0.359375    3.125000 -0.258065
J -0.252874   -0.863636  2.782609
K -0.353846    5.444444 -0.609195
L -0.500000    0.396552 -0.411765
M  0.523810   -0.037037  1.950000
N  0.187500   -0.089744 -0.118644
O -0.657895   -0.112676 -0.576923
P  5.230769   -0.761905  2.090909
Q -0.753086    5.066667 -0.808824
R -0.400000   -0.890110  4.307692
S  4.833333    8.600000 -0.391304
T -0.900000   -0.750000  0.119048
U  8.857143   -0.541667  0.340426

In [132]:
df.cov() # 属性的协⽅差

                Python   Tensorflow       Keras
Python      718.786842  -354.257895  159.905263
Tensorflow -354.257895  1194.726316 -335.547368
Keras       159.905263  -335.547368  551.326316

In [133]:
# demo:
df['Python'].cov(df['Keras']) # Python和Keras的协⽅差

np.float64(159.90526315789475)

In [134]:
df.corr() # 所有属性相关性系数

              Python  Tensorflow     Keras
Python      1.000000   -0.382283  0.254014
Tensorflow -0.382283    1.000000 -0.413443
Keras       0.254014   -0.413443  1.000000

In [135]:
# demo:
df.corrwith(df['Tensorflow']) # 单⼀属性相关性系数

Python       -0.382283
Tensorflow    1.000000
Keras        -0.413443
dtype: float64